// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOR8VpEf_71m4JMLfSHo_wvQ_c5giAgIs',
    appId: '1:584731844750:web:16356d755af573ca78a9df',
    messagingSenderId: '584731844750',
    projectId: 'itistore-7fac4',
    authDomain: 'itistore-7fac4.firebaseapp.com',
    storageBucket: 'itistore-7fac4.appspot.com',
    measurementId: 'G-32NX1W8RL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzCeYMByqbfcXNSYrlJZZWPGyjomiY_Vo',
    appId: '1:584731844750:android:84e84e2092cfdc8678a9df',
    messagingSenderId: '584731844750',
    projectId: 'itistore-7fac4',
    storageBucket: 'itistore-7fac4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1hrlvlMS4tdxsbRkMGWzvmXFHEFDdZaM',
    appId: '1:584731844750:ios:58021a207c41c22478a9df',
    messagingSenderId: '584731844750',
    projectId: 'itistore-7fac4',
    storageBucket: 'itistore-7fac4.appspot.com',
    iosClientId: '584731844750-4iuc1h5ae09j13roa0jmhtrv2riue4j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.itistore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1hrlvlMS4tdxsbRkMGWzvmXFHEFDdZaM',
    appId: '1:584731844750:ios:ed0b810cb1d42a2378a9df',
    messagingSenderId: '584731844750',
    projectId: 'itistore-7fac4',
    storageBucket: 'itistore-7fac4.appspot.com',
    iosClientId: '584731844750-1v37so674q8bg7eodvkebaeufqevsmiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.itistore.RunnerTests',
  );
}
